"""Rebuild proofs, audit assumptions, exercise the CLI and mutate isolated copies."""
from __future__ import annotations

import argparse
import copy
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parent
FOUNDATIONS = {"propext", "Classical.choice", "Quot.sound"}
CASES = [
    "empty_domain", "unattained_query", "homogeneous_true", "homogeneous_false",
    "mixed_fibre", "visible_filter", "opposite_visible_filter", "duplicate_world",
    "permuted_mixed", "incomplete_positive", "expanded_ambiguous", "skeleton_retained",
]


def require(condition, message):
    if not condition:
        raise RuntimeError(message)


def lean_code(body):
    """Mask nested comments and ordinary strings, preserving source positions.

    This is a lexical gate, not a Lean parser or environment enumerator.
    Raw/interpolated strings, quotations and escaped identifiers are unsupported.
    """
    masked = list(body)
    i = 0
    while i < len(body):
        start = i
        if body.startswith("--", i):
            end = body.find("\n", i)
            i = len(body) if end < 0 else end
        elif body.startswith("/-", i):
            depth = 1
            i += 2
            while i < len(body) and depth:
                if body.startswith("/-", i):
                    depth += 1
                    i += 2
                elif body.startswith("-/", i):
                    depth -= 1
                    i += 2
                else:
                    i += 1
            require(depth == 0, "inventory: unterminated block comment")
        elif body[i] == '"':
            require(i == 0 or not (body[i - 1].isalnum() or body[i - 1] in "_!#'"),
                    "inventory: raw/interpolated strings unsupported")
            i += 1
            while i < len(body) and body[i] != '"':
                i += 2 if body[i] == "\\" else 1
            require(i < len(body), "inventory: unterminated string")
            i += 1
        else:
            require(body[i] not in chr(96) + "«»", "inventory: quotation/escaped identifier unsupported")
            i += 1
            continue
        for j in range(start, i):
            if masked[j] != "\n":
                masked[j] = " "
    return "".join(masked)


def theorem_declarations(body):
    """Inventory this package's plain-theorem dialect, rejecting unsupported forms.

    Only plain ASCII theorem names inside one ObservationEngine namespace are supported.
    This inventories direct source declarations in the fixed library modules;
    it does not enumerate declarations generated by imported metaprograms.
    Extending this source dialect requires extending the gate or replacing it
    with an inventory from Lean's environment.
    """
    code = lean_code(body)
    forbidden = re.search(
        r"\b(?:private|protected|nonrec|lemma|axiom|axioms|sorry|sorryAx|admit|"
        r"unsafe|macro|macro_rules|syntax|elab|elab_rules|run_elab|run_tac|initialize|"
        r"builtin_initialize|section|attribute|local)\b|@\s*\[", code)
    require(forbidden is None, "inventory: unsupported proof syntax" +
            (": " + forbidden.group() if forbidden else ""))
    scopes = [match for match in re.finditer(r"\b(?:namespace|end)\b[^\n]*", code)]
    require(not scopes or [match.group().strip() for match in scopes] ==
            ["namespace ObservationEngine", "end ObservationEngine"], "inventory: unsupported namespace/scope")
    declarations = []
    positions = set()
    for match in re.finditer(
            r"^theorem ([A-Za-z_][A-Za-z0-9_]*)(?=[ \t:({\n])", code, re.M):
        require(len(scopes) == 2 and scopes[0].end() <= match.start() < scopes[1].start(),
                "inventory: theorem outside declared namespace")
        declarations.append((match.group(1), code.count("\n", 0, match.start()) + 1))
        positions.add(match.start())
    tokens = {match.start() for match in re.finditer(r"\btheorem\b", code)}
    require(tokens == positions, "inventory: unsupported theorem declaration")
    return declarations


def theorem_names(root):
    names = []
    sources = [root / "ObservationEngine.lean", *sorted((root / "ObservationEngine").rglob("*.lean"))]
    for path in sources:
        body = path.read_text(encoding="utf-8")
        names.extend("ObservationEngine." + name for name, _ in theorem_declarations(body))
    require(names and len(names) == len(set(names)), "theorem inventory invalid")
    return set(names)


def first_error_location(output):
    """Return the first compiler error, never a warning or later replacement."""
    for raw in output.splitlines():
        line = raw.strip()
        if line.startswith("error:"):
            match = re.fullmatch(r"error:\s+(.+\.lean):(\d+):\d+:.*", line)
            require(match is not None, "proof rejection: first error has no source location")
            return match.group(1), int(match.group(2))
        match = re.match(r"^(.+\.lean):(\d+):\d+:\s*error:", line)
        if match:
            return match.group(1), int(match.group(2))
    raise RuntimeError("proof rejection: no error diagnostic")


def first_rejected_theorem(output, proof_text):
    file, line = first_error_location(output)
    require(file.replace("\\", "/").rsplit("/", 1)[-1] == "Correctness.lean",
            "proof rejection: first error is outside Correctness.lean")
    declarations = [(name, start) for name, start in theorem_declarations(proof_text) if start <= line]
    require(declarations, "proof rejection: first error precedes theorems")
    return declarations[-1][0]


def audit_axioms(output, expected):
    found = {}
    for line in output.splitlines():
        match = re.fullmatch(r"'([^']+)' (?:depends on axioms: \[([^]]*)\]|does not depend on any axioms)", line.strip())
        require(match is not None, "unrecognised axiom-audit output: " + line)
        name, deps = match.groups()
        require(name not in found, "duplicate theorem in axiom audit")
        used = {x.strip() for x in (deps or "").split(",") if x.strip()}
        require(used <= FOUNDATIONS, "unapproved proof dependency: " + repr(used - FOUNDATIONS))
        found[name] = used
    require(set(found) == expected, "axiom audit does not cover exact theorem inventory")


def audit_controls():
    valid = "'demo' depends on axioms: [propext, Classical.choice, Quot.sound]"
    audit_axioms(valid, {"demo"})
    for bad, expected in [
        ("'demo' depends on axioms: [sorryAx]", {"demo"}),
        ("'demo' depends on axioms: [inventedAssumption]", {"demo"}),
        (valid, {"demo", "omitted"}),
        (valid + "\n" + valid, {"demo"}),
    ]:
        try:
            audit_axioms(bad, expected)
        except RuntimeError:
            continue
        raise RuntimeError("axiom-audit negative control survived")


def verifier_controls():
    """Named positive/negative controls for the two verifier boundaries."""
    plain = "namespace ObservationEngine\ntheorem kept : True := by trivial\nend ObservationEngine"
    require(theorem_declarations(plain) == [("kept", 2)], "inventory_plain")
    harmless = (
        'namespace ObservationEngine\n'
        '/- private theorem /- sorry -/ ignored -/\n'
        '-- axiom ignored : False\n'
        'def label : String := "private theorem ignored : False := by sorry"\n'
        'theorem kept : True := by trivial\n'
        'end ObservationEngine')
    require(theorem_declarations(harmless) == [("kept", 5)], "inventory_comment_string_overfire")
    negative = [
        ("private", plain.replace("theorem kept", "private theorem kept"), "unsupported proof syntax"),
        ("attribute", plain.replace("theorem kept", "@[simp]\ntheorem kept"), "unsupported proof syntax"),
        ("lemma", plain.replace("theorem kept", "lemma kept"), "unsupported proof syntax"),
        ("axiom", plain.replace("theorem kept : True := by trivial", "axiom kept : True"), "unsupported proof syntax"),
        ("sorry", plain.replace("by trivial", "by sorry"), "unsupported proof syntax"),
        ("multiline", plain.replace("theorem kept", "theorem\nkept"), "unsupported theorem declaration"),
        ("namespace", plain.replace("ObservationEngine", "Hidden"), "unsupported namespace/scope"),
        ("outside", plain + "\ntheorem stray : True := by trivial", "outside declared namespace"),
        ("unterminated_comment", plain + "\n/-", "unterminated block comment"),
        ("unterminated_string", plain + '\n"oops', "unterminated string"),
        ("interpolation", plain + '\ndef label := s!"{by sorry}"', "raw/interpolated strings unsupported"),
    ]
    for name, text, expected in negative:
        try:
            theorem_declarations(text)
        except RuntimeError as error:
            require(expected in str(error), "inventory_" + name + ": wrong refusal")
        else:
            raise RuntimeError("inventory_" + name + ": negative control survived")
    proof = ("namespace ObservationEngine\n"
             "theorem expected : True := by trivial\n"
             "theorem other : True := by trivial\n"
             "end ObservationEngine")
    warning_then_error = (
        "warning: ObservationEngine/Correctness.lean:2:1: unused argument\n"
        "error: ObservationEngine/Correctness.lean:3:1: unsolved goals")
    require(first_rejected_theorem(warning_then_error, proof) == "other",
            "diagnostic_warning_attributed_as_error")
    require(first_rejected_theorem(
        "ObservationEngine/Correctness.lean:2:1: error: unsolved goals", proof) == "expected",
        "diagnostic_direct_format")
    require(first_rejected_theorem(
        "warning: ObservationEngine/Correctness.lean:3:1: unused argument\n"
        "error: ObservationEngine/Correctness.lean:2:1: unsolved goals", proof) == "expected",
        "diagnostic_genuine_error_overfire")
    for name, output, expected in [
        ("foreign", "error: Main.lean:1:1: other failure\n"
         "error: ObservationEngine/Correctness.lean:2:1: unsolved goals", "outside Correctness.lean"),
        ("unlocated", "error: dependency failed\n"
         "error: ObservationEngine/Correctness.lean:2:1: unsolved goals", "no source location"),
        ("warning_only", "warning: ObservationEngine/Correctness.lean:2:1: unused argument", "no error diagnostic"),
    ]:
        try:
            first_rejected_theorem(output, proof)
        except RuntimeError as error:
            require(expected in str(error), "diagnostic_" + name + ": wrong refusal")
        else:
            raise RuntimeError("diagnostic_" + name + ": negative control survived")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--lake", default="lake")
    parser.add_argument("--scratch", type=Path, required=True)
    parser.add_argument("--mutations", action="store_true")
    args = parser.parse_args()
    scratch = args.scratch.resolve()
    require(scratch != ROOT and ROOT not in scratch.parents, "scratch must be outside project")
    scratch.mkdir(parents=True, exist_ok=True)
    env = os.environ.copy()
    env["TEMP"] = str(scratch)
    env["TMP"] = str(scratch)
    counter = 0

    def run(command, cwd=ROOT, label="command", success=True):
        nonlocal counter
        counter += 1
        result = subprocess.run(
            [str(x) for x in command], cwd=cwd, env=env,
            capture_output=True, text=True, encoding="utf-8", errors="strict", timeout=300,
        )
        output = result.stdout + result.stderr
        (scratch / f"{counter:03d}-{label}.log").write_text(output, encoding="utf-8")
        if success:
            require(result.returncode == 0, f"{label} failed ({result.returncode}):\n{output}")
        return result, output

    audit_controls()
    print("PASS axiom_audit_controls", flush=True)
    verifier_controls()
    theorem_names(ROOT)
    print("PASS verifier_selfcontrols", flush=True)
    run([args.lake, "build"], label="build")
    print("PASS build", flush=True)
    _, audit = run([args.lake, "env", "lean", "AxiomAudit.lean"], label="axioms")
    audit_axioms(audit, theorem_names(ROOT))
    print(f"PASS proof_dependencies {len(theorem_names(ROOT))}", flush=True)
    _, runtime = run([args.lake, "env", "lean", "--run", "Tests.lean"], label="cases")
    require(re.findall(r"^PASS (\w+)$", runtime, re.M) == CASES, "runtime case inventory mismatch")
    require("ALL CASES PASSED" in runtime, "runtime summary missing")
    print(f"PASS runtime_cases {len(CASES)}", flush=True)

    executable = ROOT / ".lake" / "build" / "bin" / (
        "observation-engine.exe" if os.name == "nt" else "observation-engine")
    require(executable.is_file(), "CLI executable missing")
    base = {
        "schema": 1, "target": "declared_relation_preserved",
        "worlds": [
            {"id": "a", "skeleton": "system-a", "observation": "projection-x", "target_holds": True},
            {"id": "b", "skeleton": "system-a", "observation": "projection-x", "target_holds": False},
        ],
        "query": {"skeleton": "system-a", "observation": "projection-x"},
    }

    cli_command = [executable]
    cli_cwd = ROOT

    def cli(name, data, expected=None, reject=False, raw=False, reason=None):
        path = scratch / (name + ".json")
        if isinstance(data, bytes):
            path.write_bytes(data)
        else:
            path.write_text(data if raw else json.dumps(data, ensure_ascii=False), encoding="utf-8")
        result, _ = run([*cli_command, path], cwd=cli_cwd, label=name, success=False)
        if reject:
            require(result.returncode == 2 and not result.stdout.strip(), name + ": wrong refusal")
            error = json.loads(result.stderr)
            require(isinstance(error.get("error"), str) and error["error"], name + ": missing error")
            if reason is not None:
                require(reason in error["error"], name + ": wrong refusal reason: " + error["error"])
            print("PASS reject_" + name, flush=True)
            return
        require(result.returncode == 0 and not result.stderr.strip(), name + ": CLI failed")
        out = json.loads(result.stdout)
        if raw:
            data = json.loads(data)
        require(out.get("schema") == 1 and out.get("target") == data["target"], name + ": identity mismatch")
        require(out.get("scope") == "supplied_compatible_worlds", name + ": scope lost")
        require(out.get("query") == data["query"] and out.get("verdict") == expected, name + ": verdict mismatch")
        matching = [w for w in data["worlds"] if all(w[k] == data["query"][k] for k in ("skeleton", "observation"))]
        require(out.get("matching_world_ids") == [w["id"] for w in matching], name + ": wrong fibre")
        if expected == "insufficient_basis":
            witness = out.get("witness", {})
            by_id = {w["id"]: w for w in matching}
            require(witness.get("true_world_id") in by_id and witness.get("false_world_id") in by_id, name + ": witness absent")
            require(by_id[witness["true_world_id"]]["target_holds"] is True and
                    by_id[witness["false_world_id"]]["target_holds"] is False, name + ": witness invalid")
        else:
            require("witness" not in out, name + ": spurious witness")
        print("PASS cli_" + name, flush=True)

    cli("mixed", base, "insufficient_basis")
    positive = copy.deepcopy(base); positive["worlds"] = positive["worlds"][:1]
    cli("homogeneous", positive, "target_true_in_declared_fibre")
    negative = copy.deepcopy(base); negative["worlds"] = negative["worlds"][1:]
    cli("negative", negative, "target_false_in_declared_fibre")
    empty = copy.deepcopy(base); empty["worlds"] = []
    cli("empty", empty, "outside_declared_domain")
    missing = copy.deepcopy(base); missing["query"]["observation"] = "unseen"
    cli("unattained", missing, "outside_declared_domain")
    separate = copy.deepcopy(base); separate["worlds"][1]["skeleton"] = "system-b"
    cli("skeleton", separate, "target_true_in_declared_fibre")
    reversed_case = copy.deepcopy(base); reversed_case["worlds"].reverse()
    cli("permutation", reversed_case, "insufficient_basis")
    escaped = copy.deepcopy(positive); escaped["target"] = 'quote " slash \\ unicode \u03c4'
    cli("escapes", escaped, "target_true_in_declared_fibre")

    bad = copy.deepcopy(base); bad["worlds"][1]["id"] = "a"
    cli("duplicate_id", bad, reject=True, reason="duplicate id")
    bad = copy.deepcopy(base); bad["worlds"][0]["target_holds"] = "true"
    cli("wrong_type", bad, reject=True, reason="worlds[0].target_holds")
    bad = copy.deepcopy(base); bad["worlds"][0]["extra"] = True
    cli("extra_world_field", bad, reject=True, reason="worlds[0]: unknown field")
    bad = copy.deepcopy(base); bad["query"]["extra"] = True
    cli("extra_query_field", bad, reject=True, reason="query: unknown field")
    bad = copy.deepcopy(base); bad["extra"] = True
    cli("extra_root_field", bad, reject=True, reason="input: unknown field")
    bad = copy.deepcopy(base); bad["target"] = "   "
    cli("blank_target", bad, reject=True, reason="nonempty string required")
    bad = copy.deepcopy(base); del bad["query"]
    cli("missing_query", bad, reject=True, reason="input.query")
    raw_base = json.dumps(base)
    duplicate = '{"schema": 1, ' + raw_base[1:]
    escaped_duplicate = '{"sch' + chr(92) + 'u0065ma": 1, ' + raw_base[1:]
    cli("duplicate_key", duplicate, reject=True, raw=True, reason="duplicate object key")
    cli("escaped_duplicate", escaped_duplicate, reject=True, raw=True, reason="duplicate object key")
    cli("malformed", "{", reject=True, raw=True)
    cli("deep_input", "[" * 65 + "0" + "]" * 65, reject=True, raw=True, reason="JSON nesting exceeds 64")
    # At exactly the parser limit, schema validation must be the reason instead.
    cli("depth_boundary", "[" * 64 + "0" + "]" * 64, reject=True, raw=True, reason="input:")
    padded = raw_base + " " * (1048576 - len(raw_base.encode("utf-8")))
    cli("byte_boundary", padded, "insufficient_basis", raw=True)
    cli("byte_over_limit", padded + " ", reject=True, raw=True, reason="input exceeds 1048576 bytes")
    cli("invalid_utf8", raw_base.encode("utf-8") + bytes([255]), reject=True, reason="not valid UTF-8")

    scalar_case = copy.deepcopy(positive)
    scalar_case["worlds"][0]["observation"] = chr(0x1F600)
    scalar_case["query"]["observation"] = chr(0x1F600)
    cli("unicode_pair", json.dumps(scalar_case), "target_true_in_declared_fibre", raw=True)
    replacement_case = copy.deepcopy(positive)
    replacement_case["worlds"][0]["observation"] = chr(0xFFFD)
    replacement_case["query"]["observation"] = chr(0xFFFD)
    cli("replacement_scalar", replacement_case, "target_true_in_declared_fibre")
    surrogate_inputs = {}
    for name, value in [("lone_high", chr(0xD800)), ("lone_low", chr(0xDC00)),
                        ("bad_pair", chr(0xD800) + "x")]:
        invalid = copy.deepcopy(replacement_case)
        invalid["worlds"][0]["observation"] = value
        surrogate_inputs[name] = json.dumps(invalid)
        cli(name, surrogate_inputs[name], reject=True, raw=True, reason="unpaired Unicode surrogate")
    print("PASS cli_rejections 17", flush=True)


    if args.mutations:
        mutations = [
            ("empty_is_yes", "| false, false => .outOfDomain", "| false, false => .yes", "empty_domain", "classify_yes_iff"),
            ("true_is_unknown", "| true, false => .yes", "| true, false => .unknown", "homogeneous_true", "classify_yes_iff"),
            ("false_is_unknown", "| false, true => .no", "| false, true => .unknown", "homogeneous_false", "classify_no_iff"),
            ("mixed_is_yes", "| true, true => .unknown", "| true, true => .yes", "mixed_fibre", "classify_yes_iff"),
            ("observation_ignored", "decide (V w = v) && decide (Q w = b)", "decide (Q w = b)", "unattained_query", "seen_iff"),
        ]
        before = {p.relative_to(ROOT): p.read_bytes() for p in ROOT.rglob("*.lean") if ".lake" not in p.parts}
        for name, old, new, expected_case, expected_proof in mutations:
            with tempfile.TemporaryDirectory(prefix="mutant-" + name + "-", dir=scratch) as td:
                require(Path(td).resolve().parent == scratch, "temporary copy escaped scratch")
                target = Path(td) / "project"
                shutil.copytree(ROOT, target, ignore=shutil.ignore_patterns(".git"))
                source = target / "ObservationEngine" / "Finite.lean"
                body = source.read_text(encoding="utf-8")
                require(body.count(old) == 1, name + ": mutation did not identify exactly one model site")
                source.write_text(body.replace(old, new), encoding="utf-8")
                run([args.lake, "build", "ObservationEngine.Finite"], cwd=target, label=name + "-compile")
                failed, output = run([args.lake, "env", "lean", "--run", "Tests.lean"],
                                     cwd=target, label=name + "-runtime", success=False)
                reds = re.findall(r"FAIL (\w+):", output)
                require(failed.returncode != 0 and reds and reds[0] == expected_case, name + ": wrong first failed case")
                failed, output = run([args.lake, "build", "ObservationEngine"], cwd=target, label=name + "-proof", success=False)
                require(failed.returncode != 0, name + ": no proof rejection")
                proof_text = (target / "ObservationEngine" / "Correctness.lean").read_text(encoding="utf-8")
                require(first_rejected_theorem(output, proof_text) == expected_proof,
                        name + ": wrong first proof rejection")
                print(f"PASS mutation {name}: first_case={expected_case}, first_proof={expected_proof}", flush=True)

        # These are targeted input-boundary regressions, not a claim that every
        # executable example has an independent mutation in the full-case order.
        cli_mutations = [
            ("drop_skeleton",
             [("(world.skeleton, world.observation)", '("", world.observation)', 1),
              ("DeclaredWorld.targetHolds request.query", 'DeclaredWorld.targetHolds ("", request.query.2)', 1),
              ("visible world = request.query", 'visible world = ("", request.query.2)', 1)],
             lambda: cli("skeleton", separate, "target_true_in_declared_fibre"),
             "skeleton: verdict mismatch"),
            ("accept_duplicate_key",
             [('if (fields.get? key).isSome then fail s!"duplicate object key: {key}"', "pure ()", 1)],
             lambda: cli("duplicate_key", duplicate, reject=True, raw=True, reason="duplicate object key"),
             "duplicate_key: wrong refusal"),
            ("reject_unique_key",
             [("(fields.get? key).isSome", "(fields.get? key).isNone", 1)],
             lambda: cli("mixed", base, "insufficient_basis"), "mixed: CLI failed"),
            ("replace_bad_surrogate",
             [('| none => fail "unpaired Unicode surrogate"', "| none => return Char.ofNat 0xFFFD", 1)],
             lambda: cli("lone_high", surrogate_inputs["lone_high"], reject=True, raw=True,
                         reason="unpaired Unicode surrogate"), "lone_high: wrong refusal"),
            ("raise_byte_limit", [("1048576", "2097152", 4)],
             lambda: cli("byte_over_limit", padded + " ", reject=True, raw=True,
                         reason="input exceeds 1048576 bytes"), "byte_over_limit: wrong refusal"),
            ("lower_byte_limit", [("1048576", "1048575", 4)],
             lambda: cli("byte_boundary", padded, "insufficient_basis", raw=True),
             "byte_boundary: CLI failed"),
            ("raise_depth_limit", [("strictValue 64", "strictValue 65", 1)],
             lambda: cli("deep_input", "[" * 65 + "0" + "]" * 65, reject=True, raw=True,
                         reason="JSON nesting exceeds 64"), "deep_input: wrong refusal reason"),
            ("lower_depth_limit", [("strictValue 64", "strictValue 63", 1)],
             lambda: cli("depth_boundary", "[" * 64 + "0" + "]" * 64, reject=True, raw=True,
                         reason="input:"), "depth_boundary: wrong refusal reason"),
            ("invalid_witness",
             [("matching.find? (fun world => !world.targetHolds)",
               "matching.find? (fun world => world.targetHolds)", 1)],
             lambda: cli("mixed", base, "insufficient_basis"), "mixed: witness invalid"),
        ]
        for name, replacements, probe, expected_failure in cli_mutations:
            with tempfile.TemporaryDirectory(prefix="mutant-" + name + "-", dir=scratch) as td:
                require(Path(td).resolve().parent == scratch, "temporary copy escaped scratch")
                target = Path(td) / "project"
                shutil.copytree(ROOT, target, ignore=shutil.ignore_patterns(".git"))
                source = target / "Main.lean"
                body = source.read_text(encoding="utf-8")
                for old, new, count in replacements:
                    require(body.count(old) == count, name + ": wrong mutation site count")
                    body = body.replace(old, new)
                source.write_text(body, encoding="utf-8")
                run([args.lake, "env", "lean", "-j", "1", "Main.lean"], cwd=target, label=name + "-compile")
                cli_command = [args.lake, "env", "lean", "-j", "1", "--run", "Main.lean"]
                cli_cwd = target
                try:
                    probe()
                except RuntimeError as error:
                    require(str(error).startswith(expected_failure), name + ": failed for foreign cause: " + str(error))
                    print(f"PASS cli_mutation {name}: {error}", flush=True)
                else:
                    raise RuntimeError(name + ": mutant survived")
                finally:
                    cli_command = [executable]
                    cli_cwd = ROOT
        print(f"PASS targeted_cli_mutations {len(cli_mutations)}", flush=True)

        after = {p.relative_to(ROOT): p.read_bytes() for p in ROOT.rglob("*.lean") if ".lake" not in p.parts}
        require(before == after, "mutation run modified the real project")
        print(f"PASS isolated_mutations {len(mutations)}", flush=True)
    print("VERIFIED DECLARED SCOPE", flush=True)


if __name__ == "__main__":
    main()
